// Date: 5/10/2014 4:48:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMermaid extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer tail;
    ModelRenderer fin;
    ModelRenderer finc1;
    ModelRenderer finc2;
    ModelRenderer finc2c1;
    ModelRenderer finc2c2;
    ModelRenderer finc2c3;
    ModelRenderer finc2c4;
  
  public ModelMermaid()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 1F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, -0.0174533F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0.3141593F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 0, 32);
      tail.addBox(-4F, 0F, -1F, 8, 12, 3);
      tail.setRotationPoint(0F, 10F, 3F);
      tail.setTextureSize(64, 64);
      tail.mirror = true;
      setRotation(tail, 1.151917F, 0F, 0F);
      fin = new ModelRenderer(this, 32, 0);
      fin.addBox(-3F, 0F, 0F, 6, 1, 2);
      fin.setRotationPoint(0F, 14F, 13F);
      fin.setTextureSize(64, 64);
      fin.mirror = true;
      setRotation(fin, 0F, 0F, 0F);
      finc1 = new ModelRenderer(this, 32, 0);
      finc1.addBox(-4F, 0F, 2F, 8, 1, 1);
      finc1.setRotationPoint(0F, 14F, 13F);
      finc1.setTextureSize(64, 64);
      finc1.mirror = true;
      setRotation(finc1, 0F, 0F, 0F);
      finc2 = new ModelRenderer(this, 32, 0);
      finc2.addBox(-5F, 0F, 3F, 10, 1, 2);
      finc2.setRotationPoint(0F, 14F, 13F);
      finc2.setTextureSize(64, 64);
      finc2.mirror = true;
      setRotation(finc2, 0F, 0F, 0F);
      finc2c1 = new ModelRenderer(this, 32, 0);
      finc2c1.addBox(-6F, 0F, 5F, 3, 1, 3);
      finc2c1.setRotationPoint(0F, 14F, 13F);
      finc2c1.setTextureSize(64, 64);
      finc2c1.mirror = true;
      setRotation(finc2c1, 0F, 0F, 0F);
      finc2c2 = new ModelRenderer(this, 32, 0);
      finc2c2.addBox(3F, 0F, 5F, 3, 1, 3);
      finc2c2.setRotationPoint(0F, 14F, 13F);
      finc2c2.setTextureSize(64, 64);
      finc2c2.mirror = true;
      setRotation(finc2c2, 0F, 0F, 0F);
      finc2c3 = new ModelRenderer(this, 32, 0);
      finc2c3.addBox(-3F, 0F, 5F, 1, 1, 1);
      finc2c3.setRotationPoint(0F, 14F, 13F);
      finc2c3.setTextureSize(64, 64);
      finc2c3.mirror = true;
      setRotation(finc2c3, 0F, 0F, 0F);
      finc2c4 = new ModelRenderer(this, 32, 0);
      finc2c4.addBox(2F, 0F, 5F, 1, 1, 1);
      finc2c4.setRotationPoint(0F, 14F, 13F);
      finc2c4.setTextureSize(64, 64);
      finc2c4.mirror = true;
      setRotation(finc2c4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    tail.render(f5);
    fin.render(f5);
    finc1.render(f5);
    finc2.render(f5);
    finc2c1.render(f5);
    finc2c2.render(f5);
    finc2c3.render(f5);
    finc2c4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
